version: '3.8'

services:

  webapp:
    build:
      dockerfile: ./WebApp.Server/Dockerfile
    container_name: webapp
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080   
    restart: always

volumes:
  mongodb_data:
