<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dsr.Architecture.Application" Version="1.0.2" />
    <PackageReference Include="Dsr.Architecture.Infrastructure.Persistence" Version="1.0.8" />
    <PackageReference Include="Dsr.Architecture.TryCatch" Version="1.0.0" />
  </ItemGroup>

</Project>
