// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Infrastructure;

#nullable disable

namespace WebApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250730040101_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("WebApp.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Client");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a8a7e4a-72db-4c51-8a6a-3a3a3a3a3a3a"),
                            CreateDate = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            Enable = true,
                            Name = "John Doe",
                            Phone = "+57 3123456789"
                        },
                        new
                        {
                            Id = new Guid("2b8b8f5b-83ec-5d62-9b7b-4b4b4b4b4b4b"),
                            CreateDate = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            Enable = true,
                            Name = "Jane Smith",
                            Phone = "+57 3212345678"
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca2f98e5-fd16-472e-8384-e28f615a9769"),
                            CreateDate = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Enable = true,
                            ProductId = new Guid("3c9c9c6c-94fd-4e73-ac8c-5c5c5c5c5c5c"),
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = new Guid("3352e4c0-f5c7-4f9e-9b5c-d73716c64e42"),
                            CreateDate = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Enable = true,
                            ProductId = new Guid("4d0d0d7d-05de-4f84-bd9d-6d6d6d6d6d6d"),
                            StockQuantity = 50
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c9c9c6c-94fd-4e73-ac8c-5c5c5c5c5c5c"),
                            CreateDate = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Personal computer macbook",
                            Enable = true,
                            Name = "Laptop",
                            Price = 1200m
                        },
                        new
                        {
                            Id = new Guid("4d0d0d7d-05de-4f84-bd9d-6d6d6d6d6d6d"),
                            CreateDate = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Computer mouse",
                            Enable = true,
                            Name = "Mouse",
                            Price = 25m
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Sale");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e1e1e8e-16df-4a95-ce0e-7e7e7e7e7e7e"),
                            ClientId = new Guid("1a8a7e4a-72db-4c51-8a6a-3a3a3a3a3a3a"),
                            CreateDate = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Enable = true,
                            SaleDate = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Entities.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItem");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f2f2f9f-27fa-4c06-df1f-8f8f8f8f8f8f"),
                            CreateDate = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Enable = true,
                            ProductId = new Guid("3c9c9c6c-94fd-4e73-ac8c-5c5c5c5c5c5c"),
                            Quantity = 1,
                            SaleId = new Guid("5e1e1e8e-16df-4a95-ce0e-7e7e7e7e7e7e"),
                            UnitPrice = 1200m
                        },
                        new
                        {
                            Id = new Guid("7a3a3c0a-38ab-4e17-ea2a-9a9a9a9a9a9a"),
                            CreateDate = new DateTime(2024, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Enable = true,
                            ProductId = new Guid("4d0d0d7d-05de-4f84-bd9d-6d6d6d6d6d6d"),
                            Quantity = 1,
                            SaleId = new Guid("5e1e1e8e-16df-4a95-ce0e-7e7e7e7e7e7e"),
                            UnitPrice = 25m
                        });
                });

            modelBuilder.Entity("WebApp.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("WebApp.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.Sale", b =>
                {
                    b.HasOne("WebApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.SaleItem", b =>
                {
                    b.HasOne("WebApp.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Domain.Entities.Sale", null)
                        .WithMany("Items")
                        .HasForeignKey("SaleId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApp.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
